name: 'Jira Ticket Status'
description: 'Get the status of a Jira Ticket'
icon: 'check-circle'
color: 'blue'
  expected_status: # id of input
    description: 'The expected status of the ticket. I.e. "In Review'
    default: "In Review"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
